#!/bin/bash
echo 'Checking out develop branch to base deployment from it.'
git checkout develop

echo 'Started building process.'
ng build -prod

git branch -f gh-pages
git checkout gh-pages
echo 'Created and Checked out gh-pages branch'

git reset --hard origin/develop

cp -r dist/* .
sed -i '' 's:<base href=\"/\">:<base href=\"/\">:' index.html
echo 'Copied dist/ directory into root dir and replaced <base href="/"> with <base href="/"> in index.html'

git add -A .
echo 'Commiting files'
git commit -a -m 'github pages update'
echo 'Pushing files into public master branch'
git push public master --force